# data_path: ./
data_path: /media/gjw/Elements/slam_data       # 数据存放路径
# 关键帧
key_frame_distance: 2.0  # 关键帧距离

# 优化
graph_optimizer_type: g2o

use_gnss: true
use_loop_close: true

optimize_step_with_key_frame: 100 # 没有其他消息时，每隔step 发送一次优化位姿
optimize_step_with_gnss: 100 # 每累计step 个gnss观测时，优化一次
optimize_step_with_loop: 5  # 每累计step 个闭环约束时优化一次

g2o_param:
    odom_edge_noise: [0.5, 0.5, 0.5, 0.001, 0.001, 0.001] #噪声 x,y,z,yaw,roll,pitch
    close_loop_noise: [2.0, 2.0, 2.0, 0.01, 0.01, 0.01] #噪声 x,y,z,yaw,roll,pitch
    gnss_noise: [2, 2, 2] #噪声 x,y,z